
name: Shantharam Shenoy
description: "Shantharam's blog about programming - Ruby, Rails."
url: https://shantharamshenoy.github.io/
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

theme:
  disqus_shortname: shantharamsk
  

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
